name: ${project.artifactId}
version: ${project.version}
description: ${project.description}
author: Sam Hum
api-version: 1.13
main: edu.whimc.NPCMover.NPCMover
softdepend: [Citizens]
commands:
  novicespawn:
    description: Spawn a novice NPC with name
    usage: '/novicespawn [text]'
  expertspawn:
    description: Spawn a expert NPC with name
    usage: '/expertspawn [text]'
