name: ${project.artifactId}
version: ${project.version}
description: ${project.description}
author: Sam Hum
api-version: 1.13
main: edu.whimc.overworld_agent.OverworldAgent
softdepend: [Citizens]
commands:
  agent:
    description: Root agent command
    usage: '/agent'